version: '3.8'

services:
  db:
    image: postgres:15
    container_name: mini_pedidos_db
    restart: always
    environment:
      # Variáveis do serviço 'db' (PostgreSQL) - Já estavam aqui
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mini_pedidos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: mini_pedidos_backend
    restart: always
    ports:
      - "3001:3001"

    environment:
      # Configurações do Banco de Dados
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mini_pedidos?schema=public"
      
      # Configurações do Servidor
      PORT: 3001
      NODE_ENV: development
      
      # Configurações de CORS
      CORS_ORIGIN: "http://localhost:3000"
      
      # Configurações do Prisma
      PRISMA_GENERATE_DATAPROXY: false
      PRISMA_CLIENT_ENGINE_TYPE: binary
      
      # Configurações de JWT
      JWT_SECRET: "sua_chave_secreta_jwt_aqui_mude_em_producao"
      JWT_EXPIRES_IN: "24h"
      
      # Configurações de API
      API_VERSION: "v1"
      API_PREFIX: "/api"
      
      # Configurações de Log
      LOG_LEVEL: "info"
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm run start"

  frontend:
    build: ./frontend
    container_name: mini_pedidos_frontend
    restart: always
    ports:
      - "3000:3000"
 
    environment:
      # Configurações da API
      NEXT_PUBLIC_API_URL: "http://backend:3001"
      NEXT_PUBLIC_API_VERSION: "v1"
      
      # Configurações do Next.js
      NODE_ENV: "development"
      NEXT_TELEMETRY_DISABLED: "1"
      
      # Configurações de CORS (para desenvolvimento)
      NEXT_PUBLIC_CORS_ORIGIN: "http://localhost:3000"
      
      # Configurações de Build
      NEXT_PUBLIC_APP_NAME: "Mini Pedidos"
      NEXT_PUBLIC_APP_VERSION: "1.0.0"
    depends_on:
      - backend

volumes:
  pgdata: